<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use App\Http\Helpers\SmsHelper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log as FacadesLog;
use App\Jobs\TransactionMpesaUpdates;
use App\Models\Opt;
use App\Jobs\CustomerUpdates;
use App\Models\Blacklist;
use App\Models\Customer;
use App\Jobs\ProcessLanguage;
use App\Jobs\ProcessMpesaDaily;
use App\Models\Content;
use App\Models\ContentType;
use App\Models\Enticement;
use App\Models\Log;
use App\Models\Product;
use App\Models\Transaction;
use Carbon\Carbon;
use App\Models\Subscription;

class CallBackController extends Controller
{
    public function callbacksrequests(Request $request)
    {

        // FacadesLog::info($request);
        //reference code generated by system 
        $code = Opt::getCode();

        //icg can be airtime or Mpesa 
        if ($request->output_PaymentChannel == 'M-Pesa' || $request->output_PaymentChannel == 'Airtime') {

            //post data to update the transaction status 

	        TransactionMpesaUpdates::dispatchSync($request->output_ConversationID, $request->output_ResponseCode, $request->output_Receipt, $request->output_ResponseDesc,abs($request->output_ChargedAmount));

            if ($request->output_ResponseCode == '0') {
                //update users info and add to the subscription lists
                // CustomerUpdates::dispatch($request->output_ConversationID);

                $resp = array(
                    "output_ResponseCode" => "0",
                    "output_ResponseDesc" => "Success",
                    "output_OriginatorConversationID" => $request->output_OriginatorConversationID,
                    "output_ConversationID" => $request->output_ConversationID
                );
                return response()->json($resp);
            } else {
                $resp = array(
                    "output_ResponseCode" => "-1",
                    "output_ResponseDesc" => "Failure",
                    "output_OriginatorConversationID" => $request->output_OriginatorConversationID,
                    "output_ConversationID" => $request->output_ConversationID
                );
                return response()->json($resp);
            }
        }

        //check if the product is defined in the system
        $product = Product::where('product_ID', $request->input_ProductID)->get()->first();

        if ($request->input_RequestType == 'Bulk Opt-Out') {
            $customer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
            if ($customer) {
                if ($customer->status != -1 || $customer->ivr_status != -1) {
                    $customer->status = -1;
                    $customer->ivr_status = -1;
                    $customer->enticement = 0;
                    $customer->ivr_enticement = 0;
                    $customer->updated_at = Carbon::now();
                    $customer->save();

                    $opt = new Opt();
                    $opt->customer_ID = $customer->id;
                    $opt->opt_value = 0;
                    $opt->date = Opt::getServertime();
		    $opt->save();

		    $subscribeid = Subscription::where('customer_ID', $customer->id)->get()->first();
                    if ($subscribeid) {
                        $subscribeid->delete();
                    }


                    $sw = 'Umefanikiwa kikamilifu kijitoa kwenye huduma zote za Vodacom Afyacall.kujiunga tena neno AFYASMS /AFYAIVR kwenda 15723.';
                    $en = 'You have successfully unsubscribed to all Vodacom Afyacall services.To rejoin again send keyword AFYASMS/AFYAIVR to 15723';
                    ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                    $resp = array(
                        "output_ResponseCode" => "0",
                        "output_ResponseDesc" => "Success",
                        "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                        "output_ConversationID" => $code
                    );

                    return response()->json($resp);
                } else {

                    $resp = array(
                        "output_ResponseCode" => "-4",
                        "output_ResponseDesc" => "Already UnSubscribed",
                        "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                        "output_ConversationID" => $code
                    );

                    return response()->json($resp);
                }
            }
        }

        if ($product) {
            //customer is opt in 
            if ($request->input_RequestType == 'Opt-In') {
                //start process the IVR requests
                if ($product->name == 'IVR') {
                    $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        //if the existing customer has status of 0 or -1
                        if ($exitscostumer->ivr_status != 1) {
                            $exitscostumer->ivr_status = 0;
                            $exitscostumer->ivr_enticement = 1;
                            $exitscostumer->save();

                            //update the customer history
                            $opt = new Opt();
                            $opt->customer_ID = $exitscostumer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 1;
                            $opt->date = Opt::getServertime();
                            $opt->save();


                            //remove the customer in a list of enticement 
                            $enticement = Enticement::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                            if ($enticement) {
                                $enticement->delete();
                            }

                            $sw = 'Karibu katika huduma ya Afyacall. Utasilikiza dondoo mbalimbali kuhusu afya yako kila siku kwa kupiga 0900011111 kwa Gharama ya Tsh.300/IVR.';
                            $en = 'Welcome on Vodacom Afyacall Service. You will be able to listen various tips about your health daily dial 0900011111 at a cost of TZS 300/IVR.';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

			  ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)->onQueue('high')->delay(now()->addSeconds(10));

                            $resp = array(
                                "output_ResponseCode" => "0",
                                "output_ResponseDesc" => "Success",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            //push charging to a customer after a successfully opt-in via ICG 

                            return response()->json($resp);
                        } else {

                            $sw = 'Tayari umejiunga na huduma hii piga namba 0900011111 kusikiliza dondoo za afya kwa gharama ya Tsh 300/IVR.';
                            $en = 'You are already subscribed to this service dial 0900011111 to listen to health tips at a cost of Tsh 300 /IVR.';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            $resp = array(
                                "output_ResponseCode" => "-4",
                                "output_ResponseDesc" => "Already Subscribed",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );
                            return response()->json($resp);
                        }
                    } else {
                        //register customer
                        $customer = new Customer();
                        $customer->msisdn = $request->input_CustomerMSISDN;
                        $customer->registered_at = Opt::getServertime();
                        $customer->ivr_status = 0;
                        $customer->ivr_enticement = 1;
                        $customer->product_id = $product->id;
                        $customer->save();

                        $opt = new Opt();
                        $opt->customer_ID = $customer->id;
                        $opt->product_ID = $product->id;
                        $opt->opt_value = 1;
                        $opt->date = Opt::getServertime();
                        $opt->save();

                        //remove the customer in a list of enticement 
                        $enticement = Enticement::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                        if ($enticement) {
                            $enticement->delete();
                        }

                        $sw = 'Karibu katika huduma ya Afyacall. Utasilikiza dondoo mbalimbali kuhusu afya yako kila siku kwa kupiga 0900011111 kwa Gharama ya Tsh.300/IVR/siku.';
                        $en = 'Welcome on Vodacom Afyacall Service. You will be able to listen  various tips about your health daily dial 0900011111 at a cost of TZS 300/IVR /day.';
                        ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

			ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)->onQueue('high')->delay(now()->addSeconds(10));

                        $resp = array(
                            "output_ResponseCode" => "0",
                            "output_ResponseDesc" => "Success",
                            "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                            "output_ConversationID" => $code
                        );

                        return response()->json($resp);
                    }
                } elseif ($product->name == 'SMS') {

                    $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        //if the existing customer has status of 0 or -1
			    if ($exitscostumer->status != 1) {
			    $exitscostumer->status = 0;
                            $exitscostumer->enticement = 1;
                            $exitscostumer->save();

                            //update the customer history
                            $opt = new Opt();
                            $opt->customer_ID = $exitscostumer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 1;
                            $opt->date = Opt::getServertime();
                            $opt->save();


                            //Notify the user on success opt in
                            $sw = 'Karibu katika huduma ya Vodacom Afyacall.Utapata dondoo mbalimbali kuhusu afya yako kila siku kwa Gharama ya Tsh 150 tu. Kujitoa tuma neno ONDOASMS kwenda 15723';
                            $en = 'Welcome on Vodacom Afyacall Service. You will receive various tips about health daily at a cost of TZS 150/day.To unsubscribe send the word ONDOASMS to 15723';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);
                            //push content to customer

                            // $this->sendthefirstmessage($request->input_CustomerMSISDN, $exitscostumer->content);

			  ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)->onQueue('high')->delay(now()->addSeconds(10));

                            $resp = array(
                                "output_ResponseCode" => "0",
                                "output_ResponseDesc" => "Success",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            return response()->json($resp);
                        } else {
                            $resp = array(
                                "output_ResponseCode" => "-4",
                                "output_ResponseDesc" => "Already Subscribed",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            return response()->json($resp);
                        }
                    } else {
                        //register customer
                        $customer = new Customer();
                        $customer->msisdn = $request->input_CustomerMSISDN;
                        $customer->registered_at = Opt::getServertime();
                        $customer->enticement = 1;
                        $customer->status = 0;
                        $customer->product_id = $product->id;
                        $customer->save();

                        //update other info ?? history
                        $opt = new Opt();
                        $opt->customer_ID = $customer->id;
                        $opt->product_ID = $product->id;
                        $opt->opt_value = 1;
                        $opt->date = Opt::getServertime();
                        $opt->save();


                        //remove the customer in a list of enticement 
                        $enticement = Enticement::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                        if ($enticement) {
                            $enticement->delete();
                        }

                        //Notify the user on success opt in
                        $sw = 'Karibu katika huduma ya Vodacom Afyacall.Utapata dondoo mbalimbali kuhusu afya yako kila siku kwa Gharama ya Tsh 150 tu. Kujitoa tuma neno ONDOASMS kwenda 15723';
                        $en = 'Welcome on Vodacom Afyacall Service. You will receive various tips about health daily at a cost of TZS 150/day.To unsubscribe send the word ONDOASMS to 15723';
                        ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                        //push content to customer 
                        // $this->sendthefirstmessage($request->input_CustomerMSISDN, null);

			ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)->onQueue('high')->delay(now()->addSeconds(10));
                        $resp = array(
                            "output_ResponseCode" => "0",
                            "output_ResponseDesc" => "Success",
                            "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                            "output_ConversationID" => $code
                        );

                        return response()->json($resp);
                    }
                }
            } elseif ($request->input_RequestType == 'Opt-Out') {

                $customer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();

                if ($product->name == 'IVR') {
                    if ($customer) {
                        if ($customer->ivr_status != -1) {
                            $customer->ivr_status = -1;
                            $customer->ivr_enticement = 0;
                            $customer->updated_at = Carbon::now();
                            $customer->save();

                            $opt = new Opt();
                            $opt->customer_ID = $customer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 0;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            $sw = 'Umefanikiwa kujitoa kikamilifu kwenye huduma ya AFYACALL IVR. Kujiunga tena na huduma hii tuma neno AFYAIVR kwenda 15723 au piga 0900011111 kwa Tsh.300/siku';
                            $en = 'You have successfully unsubscribed from AFYACALL IVR service. To rejoin this service send the word AFYAIVR to 15723 or dial 0900011111 at a cost of Tzs 300/day';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            $resp = array(
                                "output_ResponseCode" => "0",
                                "output_ResponseDesc" => "Success",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            return response()->json($resp);
                        } else {

                            $resp = array(
                                "output_ResponseCode" => "-4",
                                "output_ResponseDesc" => "Already UnSubscribed",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );
                            return response()->json($resp);
                        }
                    }
                } else {
                    if ($customer) {
                        if ($customer->status != -1) {
                            $customer->status = -1;
                            $customer->enticement = 0;
                            $customer->updated_at = Carbon::now();
                            $customer->save();

                            $sw = 'Umefanikiwa kujitoa kikamilifu kwenye huduma ya AFYACALL SMS.Kujiunga tena na huduma hii tuma neno AFYASMS kwenda 15723 kwa gharama ya Tsh 150/siku.';
                            $en = 'You have successfully unsubscribed from AFYACALL SMS service. To rejoin this service send the word AFYASMS to 15723 at a cost of Tzs 150/day';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            Customer::updateCustomerHistory($customer->id, 0, $product->id);

                            $resp = array(
                                "output_ResponseCode" => "0",
                                "output_ResponseDesc" => "Success",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            return response()->json($resp);
                        } else {

                            $resp = array(
                                "output_ResponseCode" => "-4",
                                "output_ResponseDesc" => "Already UnSubscribed",
                                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                                "output_ConversationID" => $code
                            );

                            return response()->json($resp);
                        }
                    }
                }
            } elseif ($request->input_RequestType == 'Content Pull') {
                //send message to the customer
                $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                if ($exitscostumer) {
                    $this->sendthefirstmessage($exitscostumer->msisdn, null);
                    $resp = array(
                        "output_ResponseCode" => "0",
                        "output_ResponseDesc" => "Success",
                        "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                        "output_ConversationID" => $code
                    );

                    return response()->json($resp);
                } else {
                    $resp = array(
                        "output_ResponseCode" => "-1",
                        "output_ResponseDesc" => "Failure",
                        "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                        "output_ConversationID" => $code
                    );

                    return response()->json($resp);
                }
            }
        } else {
            $resp = array(
                "output_ResponseCode" => "-2",
                "output_ResponseDesc" => "System Internal Error",
                "output_OriginatorConversationID" => $request->input_OriginatorConversationID,
                "output_ConversationID" => $code
            );
            return response()->json($resp);
        }
    }


    function str_after($str, $search)
    {
        return $search === '' ? $str : array_reverse(explode($search, $str, 2))[0];
    }
    public function sendthefirstmessage($number, $message_content_key)
    {
        $last_sms_send = $this->last_message_sent($number);
        if ($last_sms_send) {
            $next_sms_send = $this->is_message_sent($last_sms_send, $message_content_key);
            if ($next_sms_send) {
                $smsHelper = new SmsHelper();
                $smsHelper->sendSms($number, $next_sms_send);
            }
        }
    }

    public function last_message_sent($number)
    {

        $lastmessage = Log::where('last_sent', $number)->get()->pluck('content_id');
        if (!$lastmessage->isEmpty()) {
            return $lastmessage->toArray();
        } else {
            return array(0);
        }
    }

    public function is_message_sent($message_sent_ids, $message_content_key)
    {
        $messagetype = ContentType::where('name', $message_content_key)->first();
        if ($messagetype) {
            $allmessage = Content::where('content_type', $messagetype['id'])->get();
            foreach ($allmessage as  $value) {
                if (!in_array($value->id, $message_sent_ids)) {
                    return  $value->id;
                }
            }
        } else {
            //without message keyword
            $allmessage = Content::all();
            foreach ($allmessage as  $value) {
                if (!in_array($value->id, $message_sent_ids)) {
                    return  $value->id;
                }
            }
        }
    }
}

