<?php

namespace App\Http\Controllers\Api\v1;

use App\Http\Controllers\Controller;
use App\Http\Helpers\SmsHelper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log as FacadesLog;
use App\Jobs\TransactionMpesaUpdates;
use App\Jobs\FlipEnticement;
use App\Jobs\HandleAsyncResponseJob;
use App\Jobs\HandleOptsJob;
use App\Models\Opt;
use App\Models\Content;
use App\Models\Product;
use App\Models\Customer;
use App\Models\Enticement;
use App\Models\ContentType;
use App\Models\Transaction;
use App\Models\Subscription;
use GuzzleHttp\Client;


class CallBackController extends Controller
{
    public function callbacksrequests(Request $request)
    {
        FacadesLog::info($request);
        //reference code generated by system
        $data = $request->all(); // Get response data

        // Dispatch the job synchronously
        HandleAsyncResponseJob::dispatchSync($data);
        //Flip ICG Enticement Flag
        if ($request->output_ResponseCode == "-7") {

            FlipEnticement::dispatchSync(
                $request->output_ResponseCode,
                $request->output_ResponseDesc,
                $request->output_Receipt,
                $request->output_PaymentChannel,
                $request->output_ConversationID,
                abs($request->output_ChargedAmount)
            );
        }
        // post data to update the transaction status
        TransactionMpesaUpdates::dispatchSync($request->output_ConversationID, $request->output_ResponseCode, $request->output_Receipt, $request->output_ResponseDesc, abs($request->output_ChargedAmount),$request->output_PaymentChannel );
        
        //icg can be airtime or Mpesa
        if ($request->output_PaymentChannel == 'M-Pesa' || $request->output_PaymentChannel == 'Airtime') {
            //post data to update the transaction status

            // TransactionMpesaUpdates::dispatchSync($request->output_ConversationID, $request->output_ResponseCode, $request->output_Receipt, $request->output_ResponseDesc, abs($request->output_ChargedAmount),$request->output_PaymentChannel );
            
            if ($request->output_ResponseCode == "0") {

                $resp = [
                    'output_ResponseCode' => '0',
                    'output_ResponseDesc' => 'Success',
                    'output_OriginatorConversationID' => $request->output_OriginatorConversationID,
                    'output_ConversationID' => $request->output_ConversationID,
                ];

                return response()->json($resp);
            } else {
                $resp = [
                    'output_ResponseCode' => '-1',
                    'output_ResponseDesc' => 'Failure',
                    'output_OriginatorConversationID' => $request->output_OriginatorConversationID,
                    'output_ConversationID' => $request->output_ConversationID,
                ];

                return response()->json($resp);
            }
        }

        $code = Opt::getCode();
        if ($request->input_RequestType == 'Bulk Opt-Out') {
            $customer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
            if ($customer) {

                 // send unsub reqs to BOT server
                $product1 = '921465_P01'; //bcoz currently BOT handles sms only
                $product2 = '921465_P02'; //bcoz currently BOT handles sms only
                $product3 = '921465_P03'; //bcoz currently BOT handles sms only

                 $this->unsubtobot($request->input_CustomerMSISDN, $product1);
                 $this->unsubtobot($request->input_CustomerMSISDN, $product2);
                 $this->unsubtobot($request->input_CustomerMSISDN, $product3);

                if ($customer->status != -1 || $customer->ivr_status != -1 || $customer->doctor_subscription_status != -1) {
                    $customer->status = -1;
                    $customer->ivr_status = -1;
                    $customer->doctor_subscription_status = -1;
                    $customer->enticement = 0;
                    $customer->ivr_enticement = 0;

                    $customer->save();

                    $opt = new Opt();
                    $opt->customer_ID = $customer->id;
                    $opt->opt_value = 0;
                    $opt->date = Opt::getServertime();
                    $opt->save();

                    Subscription::where('customer_ID', $customer->id)->delete();

                    $sw = 'Umefanikiwa kikamilifu kijitoa kwenye huduma zote za Vodacom Afyacall.kujiunga tena neno AFYASMS /AFYAIVR kwenda 15723.';
                    $en = 'You have successfully unsubscribed to all Vodacom Afyacall services.To rejoin again send keyword AFYASMS/AFYAIVR to 15723';
                    ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                    $resp = [
                        'output_ResponseCode' => '0',
                        'output_ResponseDesc' => 'Success',
                        'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                        'output_ConversationID' => $code,
                    ];

                    return response()->json($resp);
                } else {
                    $resp = [
                        'output_ResponseCode' => '-4',
                        'output_ResponseDesc' => 'Already UnSubscribed',
                        'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                        'output_ConversationID' => $code,
                    ];

                    return response()->json($resp);
                }
            }
        }
        //check if the product is defined in the system
        $product = Product::where('product_ID', $request->input_ProductID)->get()->first();
        if ($product) {
            //customer is opt in
            if ($request->input_RequestType == 'Opt-In') {
                //start process the IVR requests
                if ($product->product_ID == '921465_P01') {
                    $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        //if the existing customer has status of 0 or -1
                        if ($exitscostumer->ivr_status != 1) {
                            $exitscostumer->ivr_status = 0;
                            $exitscostumer->ivr_enticement = 1;
                            $exitscostumer->save();

                            //update the customer history
                            $opt = new Opt();
                            $opt->customer_ID = $exitscostumer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 1;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            $sw = 'Karibu katika huduma ya Afyacall. Utasilikiza dondoo mbalimbali kuhusu afya yako kila siku kwa kupiga 0900011111 kwa Gharama ya Tsh.300/IVR.';
                            $en = 'Welcome on Vodacom Afyacall Service. You will be able to listen various tips about your health daily dial 0900011111 at a cost of TZS 300/IVR.';
                            ProcessLanguage::dispatch($request->input_CustomerMSISDN, $sw, $en)->onQueue('high');

                            ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                                ->onQueue('high')
                                ->delay(now()->addSeconds(1));

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];

                            FacadesLog::info('ICGsubscription IVR response: ' . json_encode($resp));
                            HandleOptsJob::dispatchSync($data);

                            return response()->json($resp);
                        } else {
                            $sw = 'Tayari umejiunga na huduma hii piga namba 0900011111 kusikiliza dondoo za afya kwa gharama ya Tsh 300/IVR.';
                            $en = 'You are already subscribed to this service dial 0900011111 to listen to health tips at a cost of Tsh 300 /IVR.';
                            ProcessLanguage::dispatch($request->input_CustomerMSISDN, $sw, $en)->onQueue('high');

                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already Subscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        }
                    } else {
                        //register customer
                        $customer = new Customer();
                        $customer->msisdn = $request->input_CustomerMSISDN;
                        $customer->registered_at = Opt::getServertime();
                        $customer->ivr_status = 0;
                        $customer->ivr_enticement = 1;
                        $customer->product_id = $product->id;
                        $customer->save();

                        $opt = new Opt();
                        $opt->customer_ID = $customer->id;
                        $opt->product_ID = $product->id;
                        $opt->opt_value = 1;
                        $opt->date = Opt::getServertime();
                        $opt->save();

                        //remove the customer in a list of enticement
                        $enticement = Enticement::where('msisdn', $request->input_CustomerMSISDN)
                            ->get()
                            ->first();
                        if ($enticement) {
                            $enticement->delete();
                        }

                        $sw = 'Karibu katika huduma ya Afyacall. Utasilikiza dondoo mbalimbali kuhusu afya yako kila siku kwa kupiga 0900011111 kwa Gharama ya Tsh.300/IVR/siku.';
                        $en = 'Welcome on Vodacom Afyacall Service. You will be able to listen  various tips about your health daily dial 0900011111 at a cost of TZS 300/IVR /day.';
                        ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                        ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                            ->onQueue('high')
                            ->delay(now()->addSeconds(1));

                        $resp = [
                            'output_ResponseCode' => '0',
                            'output_ResponseDesc' => 'Success',
                            'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                            'output_ConversationID' => $code,
                        ];

                        FacadesLog::info('ICGsubscription IVR response: ' . json_encode($resp));
                        HandleOptsJob::dispatchSync($data);

                        return response()->json($resp);
                    }
                } elseif ($product->product_ID == "921465_P02") {
                    // Job for subscription requests from Docker/Chatbot server
                    // HandleOptsJob::dispatchSync($data);

                    $exitscostumer = Customer::where("msisdn", $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        //if the existing customer has status of 0 or -1
                        if ($exitscostumer->status != 1) {
                            $exitscostumer->status = 0;
                            $exitscostumer->enticement = 1;
                            $exitscostumer->save();

                            //update the customer history
                            $opt = new Opt();
                            $opt->customer_ID = $exitscostumer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 1;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            //Notify the user on success opt in
                            $sw = 'Karibu katika huduma ya Vodacom Afyacall.Utapata dondoo mbalimbali kuhusu afya yako kila siku kwa Gharama ya Tsh 150 tu. Kujitoa tuma neno ONDOASMS kwenda 15723';
                            $en = 'Welcome on Vodacom Afyacall Service. You will receive various tips about health daily at a cost of TZS 150/day.To unsubscribe send the word ONDOASMS to 15723';
                            ProcessLanguage::dispatch($request->input_CustomerMSISDN, $sw, $en)->onQueue('high');
                            //push content to customer

                            // $this->sendthefirstmessage($request->input_CustomerMSISDN, $exitscostumer->content);

                            ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                                ->onQueue('high')
                                ->delay(now()->addSeconds(1));

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info('ICGsubscription SMS response: ' . json_encode($resp));

                            HandleOptsJob::dispatchSync($data);

                            return response()->json($resp);
                        } else {
                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already Subscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        }
                    } else {
                        //register customer
                        $customer = new Customer();
                        $customer->msisdn = $request->input_CustomerMSISDN;
                        $customer->registered_at = Opt::getServertime();
                        $customer->enticement = 1;
                        $customer->status = 0;
                        $customer->product_id = $product->id;
                        $customer->save();

                        //update other info ?? history
                        $opt = new Opt();
                        $opt->customer_ID = $customer->id;
                        $opt->product_ID = $product->id;
                        $opt->opt_value = 1;
                        $opt->date = Opt::getServertime();
                        $opt->save();

                        //Notify the user on success opt in
                        $sw = 'Karibu katika huduma ya Vodacom Afyacall.Utapata dondoo mbalimbali kuhusu afya yako kila siku kwa Gharama ya Tsh 150 tu. Kujitoa tuma neno ONDOASMS kwenda 15723';
                        $en = 'Welcome on Vodacom Afyacall Service. You will receive various tips about health daily at a cost of TZS 150/day.To unsubscribe send the word ONDOASMS to 15723';
                        ProcessLanguage::dispatch($request->input_CustomerMSISDN, $sw, $en)->onQueue('high');

                        //push content to customer
                        // $this->sendthefirstmessage($request->input_CustomerMSISDN, null);

                        ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                            ->onQueue('high')
                            ->delay(now()->addSeconds(1));
                        $resp = [
                            'output_ResponseCode' => '0',
                            'output_ResponseDesc' => 'Success',
                            'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                            'output_ConversationID' => $code,
                        ];
                        FacadesLog::info('ICGsubscription New SMS response: ' . json_encode($resp));

                        HandleOptsJob::dispatchSync($data);

                        return response()->json($resp);
                    }
                } elseif ($product->product_ID == '921465_P03') {
                    $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        if ($exitscostumer->doctor_subscription_status != 1) {
                            $exitscostumer->doctor_subscription_status = 0;
                            $exitscostumer->doctor_enticement = 1;
                            $exitscostumer->save();

                            //update the customer history
                            $opt = new Opt();
                            $opt->customer_ID = $exitscostumer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 1;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            //Notify the user on success opt in
                            $messageSwahili = 'Umejiunga tena na huduma ya Kuongea na madktari wa Afyacall.Utapokea dakika moja zitazokusanywa kila siku kwa TSH 200/Siku.Kujiondoa Tuma Neno ONDOADOC Kwenda 15723.';
                            $messageEnglish = 'You have subscribed again on Afyacall Direct Doctors call Service.You will receive accumulative 1 min daily for TSH 200 per Day.To unsubscribe send ONDOADOC TO 15723.';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $messageSwahili, $messageEnglish);
                            //push content to customer

                            ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                                ->onQueue('high')
                                ->delay(now()->addSeconds(1));

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            // FacadesLog::info("=============================doctor sub=======================");
                            // FacadesLog::info($resp);
                            FacadesLog::info('ICGsubscription DOC response: ' . json_encode($resp));

                            HandleOptsJob::dispatchSync($data);

                            return response()->json($resp);
                        } else {
                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already Subscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info('=============================doctor sub failed=======================');
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        }
                    } else {
                        $customer = new Customer();
                        $customer->msisdn = $request->input_CustomerMSISDN;
                        $customer->registered_at = Opt::getServertime();
                        $customer->doctor_enticement = 1;
                        $customer->doctor_subscription_status = 0;
                        $customer->product_id = $product->id;
                        $customer->save();

                        //update other info ?? history
                        $opt = new Opt();
                        $opt->customer_ID = $customer->id;
                        $opt->product_ID = $product->id;
                        $opt->opt_value = 1;
                        $opt->date = Opt::getServertime();
                        $opt->save();

                        //send the notification to customer for succefull subscribed on doctor subs
                        $messageSwahili = 'Umejiunga na huduma ya Kuongea na madktari wa Afyacall.Utapokea dakika moja zitazokusanywa kila siku kwa TSH 200/Siku.Kujiondoa Tuma Neno ONDOADOC Kwenda 15723.';
                        $messageEnglish = 'You have subscribed Afyacall Direct Doctors call Service.You will receive accumulative 1 min daily for TSH 200 per Day.To unsubscribe send ONDOADOC TO 15723.';
                        ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $messageSwahili, $messageEnglish);

                        //push content to customer
                        // $this->sendthefirstmessage($request->input_CustomerMSISDN, null);

                        ProcessMpesaDaily::dispatch($product->product_ID, $request->input_CustomerMSISDN, $product->price)
                            ->onQueue('high')
                            ->delay(now()->addSeconds(1));
                        $resp = [
                            'output_ResponseCode' => '0',
                            'output_ResponseDesc' => 'Success',
                            'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                            'output_ConversationID' => $code,
                        ];
                        FacadesLog::info('ICGsubscription New DOC response: ' . json_encode($resp));

                        HandleOptsJob::dispatchSync($data);
                        return response()->json($resp);
                    }
                } elseif ($product->product_ID == '921465_P04') {
                    $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)->get()->first();
                    if ($exitscostumer) {
                        $resp = [
                            'output_ResponseCode' => '0',
                            'output_ResponseDesc' => 'Success',
                            'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                            'output_ConversationID' => $code,
                        ];
                        FacadesLog::info($resp);

                        return response()->json($resp);
                    } else {
                        $resp = [
                            'output_ResponseCode' => '0',
                            'output_ResponseDesc' => 'Success',
                            'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                            'output_ConversationID' => $code,
                        ];
                        FacadesLog::info($resp);

                        return response()->json($resp);
                    }
                }
            } elseif ($request->input_RequestType == "Opt-Out" || $request->input_RequestType == "Auto-Opt-Out" ) {

                $customer = Customer::where("msisdn", $request->input_CustomerMSISDN)->get()->first();
                if ($customer) {

                    // send unsub reqs to BOT server
                    $this->unsubtobot($request->input_CustomerMSISDN, $request->input_ProductID);

                    //check the products
                    if ($product->product_ID == '921465_P01') {
                        if ($customer->ivr_status != -1) {
                            $customer->ivr_status = -1;
                            $customer->ivr_enticement = 0;
                            $customer->save();

                            $opt = new Opt();
                            $opt->customer_ID = $customer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 0;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            $sw = 'Umefanikiwa kujitoa kikamilifu kwenye huduma ya AFYACALL IVR. Kujiunga tena na huduma hii tuma neno AFYAIVR kwenda 15723 au piga 0900011111 kwa Tsh.300/siku';
                            $en = 'You have successfully unsubscribed from AFYACALL IVR service. To rejoin this service send the word AFYAIVR to 15723 or dial 0900011111 at a cost of Tzs 300/day';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        } else {
                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already UnSubscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        }
                    } elseif ($product->product_ID == '921465_P02') {
                        if ($customer->status != -1) {
                            $customer->status = -1;
                            $customer->enticement = 0;
                            $customer->save();

                            $opt = new Opt();
                            $opt->customer_ID = $customer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 0;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            $sw = 'Umefanikiwa kujitoa kikamilifu kwenye huduma ya AFYACALL SMS.Kujiunga tena na huduma hii tuma neno AFYASMS kwenda 15723 kwa gharama ya Tsh 150/siku.';
                            $en = 'You have successfully unsubscribed from AFYACALL SMS service. To rejoin this service send the word AFYASMS to 15723 at a cost of Tzs 150/day';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        } else {
                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already UnSubscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];

                            return response()->json($resp);
                        }
                    } elseif ($product->product_ID == '921465_P03') {
                        if ($customer->doctor_subscription_status != -1) {
                            $customer->doctor_subscription_status = -1;
                            $customer->doctor_enticement = 0;
                            $customer->save();

                            $opt = new Opt();
                            $opt->customer_ID = $customer->id;
                            $opt->product_ID = $product->id;
                            $opt->opt_value = 0;
                            $opt->date = Opt::getServertime();
                            $opt->save();

                            $sw = 'Umefanikiwa kujitoa kikamilifu kwenye huduma ya AFYACALL DOCTOR. Kujiunga tena na huduma piga namba 0900011111.';
                            $en = 'You have successfully unsubscribed from AFYACALL Doctors Live Call service. To rejoin this service dial 0900011111.';
                            ProcessLanguage::dispatchSync($request->input_CustomerMSISDN, $sw, $en);

                            $resp = [
                                'output_ResponseCode' => '0',
                                'output_ResponseDesc' => 'Success',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];
                            FacadesLog::info($resp);

                            return response()->json($resp);
                        } else {
                            $resp = [
                                'output_ResponseCode' => '-4',
                                'output_ResponseDesc' => 'Already UnSubscribed',
                                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                                'output_ConversationID' => $code,
                            ];

                            return response()->json($resp);
                        }
                    }
                }
            } elseif ($request->input_RequestType == 'Content Pull') {
                //send message to the customer
                $exitscostumer = Customer::where('msisdn', $request->input_CustomerMSISDN)
                    ->get()
                    ->first();
                if ($exitscostumer) {
                    $this->sendthefirstmessage($exitscostumer->msisdn, null);
                    $resp = [
                        'output_ResponseCode' => '0',
                        'output_ResponseDesc' => 'Success',
                        'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                        'output_ConversationID' => $code,
                    ];

                    return response()->json($resp);
                } else {
                    $resp = [
                        'output_ResponseCode' => '-1',
                        'output_ResponseDesc' => 'Failure',
                        'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                        'output_ConversationID' => $code,
                    ];

                    return response()->json($resp);
                }
            }
        } else {
            $resp = [
                'output_ResponseCode' => '-2',
                'output_ResponseDesc' => 'System Internal Error',
                'output_OriginatorConversationID' => $request->input_OriginatorConversationID,
                'output_ConversationID' => $code,
            ];

            return response()->json($resp);
        }
    }

    public function unsubtobot($msisdn, $product_ID)
    {
        $code = Opt::getCode();

        $payload = [
            'msisdn' => $msisdn,
            'product_ID' => $product_ID,
            'request_Type' => 'Unsubscription',
            'OriginatorConversation_id' => $code
        ];

        // Log request payload as pretty JSON
        // Log::info("BOT Sending unsubscription request to https://192.168.1.200:443/api/v1/billing/icg/callback");
        FacadesLog::info("BOT unsubtobot Payload:\n" . json_encode($payload, JSON_PRETTY_PRINT));

        try {
            $client = new Client();

            $response = $client->request('POST', 'https://192.168.1.200:443/api/v1/subscriptions/etl/sms', [
                'verify' => false,
                'headers' => ['Content-Type' => 'application/json'],
                'json' => $payload
            ]);

            // Log response
            FacadesLog::info("BOT unsubtobot Response Status: " . $response->getStatusCode());
            FacadesLog::info("BOT unsubtobot Response Body:\n" . json_encode(json_decode($response->getBody(), true), JSON_PRETTY_PRINT));

            return [
                'success' => true,
                'status' => $response->getStatusCode(),
                'response' => json_decode($response->getBody(), true)
            ];

        } catch (\Exception $e) {
            // Log error
            FacadesLog::error("BOT unsubtobot Unsubscription API call failed: " . $e->getMessage());

            return [
                'success' => false,
                'message' => $e->getMessage()
            ];
        }
    }

    function str_after($str, $search)
    {
        return $search === '' ? $str : array_reverse(explode($search, $str, 2))[0];
    }

    public function sendthefirstmessage($number, $message_content_key)
    {
        $last_sms_send = $this->last_message_sent($number);
        if ($last_sms_send) {
            $next_sms_send = $this->is_message_sent($last_sms_send, $message_content_key);
            if ($next_sms_send) {
                $smsHelper = new SmsHelper();
                $smsHelper->sendSms($number, $next_sms_send);
            }
        }
    }

    public function last_message_sent($number)
    {
        $lastmessage = Log::where('last_sent', $number)
            ->get()
            ->pluck('content_id');
        if (!$lastmessage->isEmpty()) {
            return $lastmessage->toArray();
        } else {
            return [0];
        }
    }

    public function is_message_sent($message_sent_ids, $message_content_key)
    {
        $messagetype = ContentType::where('name', $message_content_key)->first();
        if ($messagetype) {
            $allmessage = Content::where('content_type', $messagetype['id'])->get();
            foreach ($allmessage as $value) {
                if (!in_array($value->id, $message_sent_ids)) {
                    return $value->id;
                }
            }
        } else {
            //without message keyword
            $allmessage = Content::all();
            foreach ($allmessage as $value) {
                if (!in_array($value->id, $message_sent_ids)) {
                    return $value->id;
                }
            }
        }
    }
}
